// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs0HgrwF9nLGaYVkNkv-tSPLa2KhktH-Y',
    appId: '1:630281506515:android:ea825cdafc8aad052e0e26',
    messagingSenderId: '630281506515',
    projectId: 'platzi-trips-flutter-ec5c4',
    storageBucket: 'platzi-trips-flutter-ec5c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC30H8IHzATKiclpgWU1D5VRrtLYv5HxDY',
    appId: '1:630281506515:ios:ef4f470a55bc5c0e2e0e26',
    messagingSenderId: '630281506515',
    projectId: 'platzi-trips-flutter-ec5c4',
    storageBucket: 'platzi-trips-flutter-ec5c4.appspot.com',
    androidClientId: '630281506515-r518j2d1c7334fledsg7vcs6n33q0m01.apps.googleusercontent.com',
    iosClientId: '630281506515-3k1pgc316o87gto6i9s83ia1ln8sqr2j.apps.googleusercontent.com',
    iosBundleId: 'com.example.cursoAvanzado',
  );
}
